name: Deploy to AWS Lambda

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # - name: Deploy Lambda Function
      #   uses: aws-actions/aws-lambda-deploy@v1.1.0
      #   with:
      #     function-name: my-function-name
      #     code-artifacts-dir: my-code-artifacts-dir
      #     handler: index.handler
      #     runtime: nodejs22.x

      # Add any additional inputs this action supports
